tp: camino_minimo.cpp bellman_ford.cpp bellman_ford.h dijkstra_cp.cpp dijkstra_cp.h dijkstra.cpp dijkstra.h floyd_warshall.cpp floyd_warshall.h funciones_auxiliares.cpp funciones_auxiliares.h estructuras.h estructuras.cpp
	g++ -g -std=c++11 -O3 camino_minimo.cpp bellman_ford.cpp dijkstra_cp.cpp dijkstra.cpp floyd_warshall.cpp funciones_auxiliares.cpp estructuras.cpp -o bin/tp

clean:
	rm -r bin/
